import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Semester, User } from '../store/useStore';
import { calculateCGPA, calculateTotalCredits } from './gpa';

export const exportToPDF = (semesters: Semester[], user: User) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Set default font
  doc.setFont('helvetica', 'normal');
  
  // Title (Centered)
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text('Academic Transcript', pageWidth / 2, 22, { align: 'center' });
  
  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by UniGrade Pro', pageWidth / 2, 28, { align: 'center' });
  
  // Overall Summary & Student Info Highlight Card
  const cgpa = calculateCGPA(semesters);
  const totalCredits = calculateTotalCredits(semesters);
  
  // Highlight card background (Soft cream color)
  doc.setFillColor(249, 248, 240);
  doc.setDrawColor(229, 227, 203);
  doc.roundedRect(14, 34, 182, 22, 3, 3, 'FD');
  
  // Student Metadata text
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(`Student Name: ${user.name}`, 20, 43);
  doc.text(`Email: ${user.email}`, 20, 50);
  
  // Solid Brand Color Highlight Box for GPA/Credits
  doc.setFillColor(158, 153, 79); // Brand color (#9e994f)
  doc.roundedRect(125, 37, 65, 16, 2, 2, 'F');
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(`CGPA: ${cgpa.toFixed(2)}`, 157.5, 43.5, { align: 'center' });
  doc.text(`Total Credits: ${totalCredits}`, 157.5, 49.5, { align: 'center' });
  
  let currentY = 68;
  
  semesters.forEach(sem => {
    // Add new page if close to bottom
    if (currentY > 240) {
      doc.addPage();
      currentY = 20;
    }

    // Semester Header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(201, 130, 207);
    doc.text(`${sem.name} - GPA: ${sem.gpa.toFixed(2)}`, 14, currentY);
    
    // Table
    const tableData = sem.subjects.map(sub => [
      sub.name || 'Unnamed Course',
      sub.credits.toString(),
      sub.grade || (sub.marks !== undefined ? sub.marks.toString() : '-'),
      sub.points.toFixed(2)
    ]);
    
    autoTable(doc, {
      startY: currentY + 5,
      head: [['Course', 'Credits', 'Grade/Marks', 'Points']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [158, 153, 79] }, // Brand color header
      margin: { left: 14 }
    });
    
    currentY = (doc as any).lastAutoTable.finalY + 15;
  });
  
  doc.save(`${user.name.replace(/\s+/g, '_')}_Transcript.pdf`);
};

export const exportSemesterToPDF = (semester: Semester, studentName: string = 'Guest Student') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Set default font
  doc.setFont('helvetica', 'normal');
  
  // Title (Centered)
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text('Semester Result Certificate', pageWidth / 2, 22, { align: 'center' });
  
  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by UniGrade Pro', pageWidth / 2, 28, { align: 'center' });
  
  const totalCredits = semester.subjects.reduce((sum, sub) => sum + (sub.credits > 0 && (sub.grade || sub.marks !== undefined) ? sub.credits : 0), 0);
  
  // Highlight card background (Soft cream color)
  doc.setFillColor(249, 248, 240);
  doc.setDrawColor(229, 227, 203);
  doc.roundedRect(14, 34, 182, 22, 3, 3, 'FD');
  
  // Metadata text
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(`Student Name: ${studentName}`, 20, 43);
  doc.text(`Semester: ${semester.name || 'Current Semester'}`, 20, 50);
  
  // Solid Brand Color Highlight Box for GPA/Credits
  doc.setFillColor(158, 153, 79); // Brand color
  doc.roundedRect(125, 37, 65, 16, 2, 2, 'F');
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(`Semester GPA: ${semester.gpa.toFixed(2)}`, 157.5, 43.5, { align: 'center' });
  doc.text(`Total Credits: ${totalCredits}`, 157.5, 49.5, { align: 'center' });
  
  const tableData = semester.subjects
    .filter(sub => sub.name.trim() !== '' || (sub.grade || sub.marks !== undefined))
    .map(sub => [
      sub.name || 'Unnamed Course',
      sub.credits.toString(),
      sub.grade || (sub.marks !== undefined ? sub.marks.toString() : '-'),
      sub.points.toFixed(2)
    ]);
  
  autoTable(doc, {
    startY: 64,
    head: [['Course', 'Credits', 'Grade/Marks', 'Points']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [158, 153, 79] }, // Brand color header
    margin: { left: 14 }
  });
  
  doc.save(`${studentName.replace(/\s+/g, '_')}_Semester_Result.pdf`);
};

export const exportCGPAToPDF = (
  semesters: { name: string; gpa: number | ''; credits: number | '' }[],
  studentName: string,
  finalCGPA: string,
  totalCredits: number
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Set default font
  doc.setFont('helvetica', 'normal');
  
  // Title (Centered)
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text('CGPA Result Certificate', pageWidth / 2, 22, { align: 'center' });
  
  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by UniGrade Pro', pageWidth / 2, 28, { align: 'center' });
  
  // Highlight card background (Soft cream color)
  doc.setFillColor(249, 248, 240);
  doc.setDrawColor(229, 227, 203);
  doc.roundedRect(14, 34, 182, 22, 3, 3, 'FD');
  
  // Metadata text
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(`Student Name: ${studentName}`, 20, 43);
  doc.text(`Overall Details Certificate`, 20, 50);
  
  // Solid Brand Color Highlight Box for CGPA/Credits
  doc.setFillColor(158, 153, 79); // Brand color
  doc.roundedRect(125, 37, 65, 16, 2, 2, 'F');
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(`Overall CGPA: ${finalCGPA}`, 157.5, 43.5, { align: 'center' });
  doc.text(`Total Credits: ${totalCredits}`, 157.5, 49.5, { align: 'center' });
  
  const tableData = semesters
    .filter(sem => sem.name.trim() !== '' || sem.gpa !== '' || sem.credits !== '')
    .map(sem => [
      sem.name || 'Unnamed Semester',
      sem.credits.toString(),
      sem.gpa.toString()
    ]);
  
  autoTable(doc, {
    startY: 64,
    head: [['Semester / Label', 'Credits', 'GPA']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [158, 153, 79] }, // Brand color header
    margin: { left: 14 }
  });
  
  doc.save(`${studentName.replace(/\s+/g, '_')}_CGPA_Result.pdf`);
};
