import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Semester, User } from '../store/useStore';
import { calculateCGPA, calculateTotalCredits } from './gpa';

export const exportToPDF = (semesters: Semester[], user: User) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text('Academic Transcript', 14, 22);
  
  // User Info
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Student Name: ${user.name}`, 14, 32);
  doc.text(`Email: ${user.email}`, 14, 38);
  doc.text(`Generated by UniGrade Pro`, 14, 44);
  
  // Overall Summary
  const cgpa = calculateCGPA(semesters);
  const totalCredits = calculateTotalCredits(semesters);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Cumulative GPA (CGPA): ${cgpa.toFixed(2)}`, 14, 55);
  doc.text(`Total Credits: ${totalCredits}`, 14, 61);
  
  let currentY = 70;
  
  semesters.forEach(sem => {
    // Add new page if close to bottom
    if (currentY > 250) {
      doc.addPage();
      currentY = 20;
    }

    // Semester Header
    doc.setFontSize(14);
    doc.setTextColor(60, 60, 60);
    doc.text(`${sem.name} - GPA: ${sem.gpa.toFixed(2)}`, 14, currentY);
    
    // Table
    const tableData = sem.subjects.map(sub => [
      sub.name || 'Unnamed Course',
      sub.credits.toString(),
      sub.grade || (sub.marks !== undefined ? sub.marks.toString() : '-'),
      sub.points.toFixed(2)
    ]);
    
    autoTable(doc, {
      startY: currentY + 5,
      head: [['Course', 'Credits', 'Grade/Marks', 'Points']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [139, 92, 246] }, // Violet-500
      margin: { left: 14 }
    });
    
    currentY = (doc as any).lastAutoTable.finalY + 15;
  });
  
  doc.save(`${user.name.replace(/\s+/g, '_')}_Transcript.pdf`);
};
